#!/usr/bin/env python3
"""Generate Codex entrypoints from shared descriptions and hook registrations."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent


def build_files() -> dict[Path, str]:
    files = {}
    for skill in sorted((ROOT / "skills").glob("*/SKILL.md")):
        frontmatter = skill.read_text(encoding="utf-8").split("---", 2)[1]
        description = re.search(r"^description: (.+)$", frontmatter, re.MULTILINE)
        if description is None:
            raise ValueError(f"Missing description: {skill}")
        name = skill.parent.name
        files[ROOT / "codex/skills" / name / "SKILL.md"] = (
            f"---\nname: {name}\ndescription: {description.group(1)}\n---\n\n"
            f"# Exactory: {name}\n\n"
            "First read [Codex runtime instructions](../../README.md).\n"
            f"Then read and execute the [shared {name} workflow](../../../skills/{name}/SKILL.md).\n"
            "Resolve that workflow's relative links from its own directory.\n"
        )
    config = json.loads((ROOT / "hooks/hooks.json").read_text(encoding="utf-8"))
    for event, groups in config["hooks"].items():
        for group in groups:
            if "Write" in group.get("matcher", "") or "Edit" in group.get("matcher", ""):
                group["matcher"] += "|apply_patch"
            for handler in group["hooks"]:
                script = handler["command"].rsplit("/", 1)[1].rstrip('"')
                handler["command"] = f'python3 "${{PLUGIN_ROOT}}/codex/hook.py" {script}'
                # Resume/stop handlers can run a 20-second harness subprocess.
                if event in ("SessionStart", "Stop"):
                    handler["timeout"] = max(handler.get("timeout", 0), 30)
    config["hooks"]["SessionStart"].insert(0, {"hooks": [{
        "type": "command",
        "command": 'python3 "${PLUGIN_ROOT}/codex/session_start.py"',
        "timeout": 10,
    }]})
    config["description"] = "Codex adapter for the shared Exactory hooks. Generated by codex/generate.py."
    files[ROOT / "codex/hooks.json"] = json.dumps(config, indent=2) + "\n"
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    args = parser.parse_args()
    files = build_files()
    stale = []
    for path, contents in files.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != contents:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8")
    expected_entries = {path for path in files if path.name == "SKILL.md"}
    stale.extend(str(path.relative_to(ROOT)) for path in
                 (ROOT / "codex/skills").glob("*/SKILL.md") if path not in expected_entries)
    if stale:
        print("Codex files need regeneration or removal: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
